### ISSUE TITLE
Build fails on "Ambiguous use of operator"

### ISSUE THREAD

**Issue by col-panic** [smart-on-fhir/SoF-MedList#7]
With XCode 9.2 the build fails stating

Ambiguous use of operator '<'
![image](https://user-images.githubusercontent.com/1679857/37206171-d8e6b9d2-2397-11e8-909b-c619ee062794.png)

**Comment by xmlmodeling** [comment]
I committed a fix by updating the Swift-SMART submodule where this compile error has been corrected.  The project now builds and runs for me in XCode 9.2

**Comment by col-panic** [comment]
I just pulled and re-openen, but I still have the same problem?! What am I doing wrong??

**Comment by xmlmodeling** [comment]
Hi Marco,

I just cloned a fresh copy of the repo and successfully built and ran the
demo app on XCode 9.2.

I suspect that you have an existing repo cloned before the change I
committed yesterday, and you pulled only updates to the immediate project,
not the nested dependencies.  The bug fix was in Swift-FHIR project that is
a nested dependency within Swift-SMART.

Try either:


git submodule update --init --recursive

git submodule foreach --recursive git fetch

Thanks,
  Dave

**Comment by col-panic** [comment]
Thanks a lot for the help - it works now :)
